#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define REFRESH_RATE 60
#define INPUTS_LENGTH (REFRESH_RATE / 2)
#define OVERRIDES_LENGTH 32
#define COMMAND_LENGTH 16
#define COMMAND_VARIATION_LENGTH 4
#define ANIMATION_LENGTH 32
#define MOVES_LENGTH 32
#define NEUTRAL_LIMIT 1
